services:
  web:
    image: nginx:1.27-bookworm
    platform: linux/amd64
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./_tools/nginx/conf.d:/etc/nginx/conf.d
      - ./_tools/nginx/certs:/etc/nginx/certs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: "Dockerfile"
      target: dev
    working_dir: /app
    platform: linux/amd64
    environment:
      CLIENT_HOST: dev-todo.citcho.com
      CLIENT_PORT: 8000
      TODO_PORT: 80
      TODO_ENV: dev
      DB_NAME: todo_db
      DB_USER: citcho
      DB_PASS: Secretp@ssw0rd
      DB_PORT: 3306
      DB_HOST: db
      TZ: "Asia/Tokyo"
      BUNDEBUG: 2
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: citcho
      MYSQL_PASSWORD: Secretp@ssw0rd
      MYSQL_ROOT_PASSWORD: Secretp@ssw0rd
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      TZ: "Asia/Tokyo"
volumes:
  db: