version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: "go.Dockerfile"
      target: dev
    working_dir: /app
    platform: linux/amd64
    environment:
      TODO_HOST: localhost
      TODO_ENV: dev
      TODO_PORT: 8080
      DB_NAME: todo_db
      DB_USER: citcho
      DB_PASS: Secretp@ssw0rd
      DB_PORT: 3306
      DB_HOST: db
      TZ: "Asia/Tokyo"
      BUNDEBUG: 2
    ports:
      - 8888:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: citcho
      MYSQL_PASSWORD: Secretp@ssw0rd
      MYSQL_ROOT_PASSWORD: Secretp@ssw0rd
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      TZ: "Asia/Tokyo"
volumes:
  db: