name: Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/checkout@v4

      - name: Create Private Key File
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ./internal/pkg/auth/cert/secret.pem
      - name: Create Public Key File
        run: |
          echo "${{ secrets.PUBLIC_KEY }}" > ./internal/pkg/auth/cert/public.pem

      - run: go test ./... -coverprofile=coverage.out

      - name: report coverage
        uses: k1LoW/octocov-action@v0

      - name: Run unit tests
        run: go test -v ./... -short

